# Visualization configuration
env:
  # id: "HalfCheetah-v5"  # MuJoCo environment ID
  id: "Humanoid-v5"  # MuJoCo environment ID
  render_mode: "human"  # "human", "rgb_array", or None
  clip_actions: 1.0      # MuJoCo humanoid 原生动作界 [-1, 1]，保持 1.0
  is_finite_horizon: false  # 保持 false，但务必修好 time_outs
  # render_mode: "None"  # "human", "rgb_array", or None
  width: 1920          # Render window width
  height: 1080          # Render window height

policy:
  checkpoint: "model_Humanoid-v5/model_1500.pt"   # 你的模型路径
  class_name: "ActorCritic"
  activation: "elu"
  actor_hidden_dims: [256, 256]
  critic_hidden_dims: [256, 256]

visualization:
  num_episodes: 10     # Number of episodes to run
  speedup: 0.01         # Simulation speed multiplier (1.0 = real-time)
  record_video: False  # Save video to files
  video_dir: "videos"  # Where to save recordings


device: "cpu"